/**
 * Resolve every album's cover art from Spotify's public oEmbed endpoint and
 * write the result to src/data/covers.ts.
 *
 *   npm run covers
 *
 * Run it whenever an album is added or a URL goes stale. Committing the output
 * keeps builds independent of Spotify being up; the build falls back to a live
 * lookup for any id that is missing here.
 */
import { readFileSync, writeFileSync } from 'node:fs';

const src = readFileSync(new URL('../src/data/discography.ts', import.meta.url), 'utf8');
const ids = [...src.matchAll(/spotifyId:\s*'([A-Za-z0-9]+)'/g)].map((m) => m[1]);
if (!ids.length) {
  console.error('No spotifyId entries found in src/data/discography.ts');
  process.exit(1);
}

const out = {};
const failed = [];
for (const id of ids) {
  try {
    const res = await fetch(`https://open.spotify.com/oembed?url=https://open.spotify.com/album/${id}`, {
      headers: { accept: 'application/json' },
    });
    if (!res.ok) throw new Error(`HTTP ${res.status}`);
    const { thumbnail_url: url } = await res.json();
    if (typeof url !== 'string') throw new Error('no thumbnail_url');
    out[id] = url;
    console.log(`ok   ${id}  ${url}`);
  } catch (e) {
    failed.push(`${id} (${e.message})`);
    console.log(`fail ${id}  ${e.message}`);
  }
}

const body = `/**
 * Album cover URLs on Spotify's image CDN, keyed by Spotify album id.
 *
 * Generated by \`npm run covers\` — do not edit by hand. Committing the result
 * means the build does not depend on Spotify being reachable; when an id is
 * missing here the build looks it up live and carries on if that fails.
 */
export const coverCache: Record<string, string> = ${JSON.stringify(out, null, 2)};
`;
writeFileSync(new URL('../src/data/covers.ts', import.meta.url), body);
console.log(`\nwrote ${Object.keys(out).length}/${ids.length} covers` + (failed.length ? `; failed: ${failed.join(', ')}` : ''));
